/*
 * Project developed by Cinthia Gonçalez
 * Educational project for elementary school English students
 *
 * All sprites are generated procedurally from inline pixel grids — no
 * copyrighted sprites are used. Each pixel character is 16×16 at
 * authoring time and rendered with crisp scaling.
 *
 * Legend used in the avatar grid string:
 *   . = transparent
 *   S = skin
 *   s = skin shade
 *   H = hair
 *   h = hair shade
 *   O = outfit (clothes)
 *   o = outfit shade
 *   A = accent (belt / sash / brooch)
 *   B = black (outline / eyes)
 *   W = white (eye highlight)
 */

import type { Avatar } from '@/types/game';

const FRAME_SIZE = 16;

interface FramePalette {
  S: string;
  s: string;
  H: string;
  h: string;
  O: string;
  o: string;
  A: string;
  B: string;
  W: string;
  R: string; // cheek (rose)
}

const grid = (s: string): string[] => {
  return s
    .replace(/\r/g, '')
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
};

const AVATAR_FRAMES: Record<Avatar['style'], { idle: string[]; walk: string[] }> = {
  'short-hair': {
    idle: grid(`
      ....HHHHHHHH....
      ...HHHHHHHHHH...
      ..HHsssssssHH...
      ..HSSSSSSSSSH...
      ..hSBSWSBSWSh...
      ..hSSSSSSSSSh...
      ..hSSRSSSSRSh...
      ..hsSSSSSSSsh...
      ...OOOOOOOOO....
      ..OOOOOOOOOOO...
      ..OOOAAAAAOOO...
      ..OOOOOOOOOOO...
      ..ooOOOOOOOoo...
      ...oo.....oo....
      ...SS.....SS....
      ...BB.....BB....
    `),
    walk: grid(`
      ....HHHHHHHH....
      ...HHHHHHHHHH...
      ..HHsssssssHH...
      ..HSSSSSSSSSH...
      ..hSBSWSBSWSh...
      ..hSSSSSSSSSh...
      ..hSSRSSSSRSh...
      ..hsSSSSSSSsh...
      ...OOOOOOOOO....
      ..OOOOOOOOOOO...
      ..OOOAAAAAOOO...
      ..OOOOOOOOOOO...
      ..ooOOOOOOOoo...
      ...oo.....oo....
      ...SS.....SSS...
      ..BB......BBB...
    `),
  },
  'long-hair': {
    idle: grid(`
      ...HHHHHHHHHH...
      ..HHHHHHHHHHHH..
      ..HHsssssssHH...
      .HHSSSSSSSSSHH..
      .HhSBSWSBSWShH..
      .HhSSSSSSSSSh...
      .HhSSRSSSSRSh...
      .HHsSSSSSSSsh...
      .HHOOOOOOOOOH...
      .HOOOOOOOOOOO...
      ..OOOAAAAAOOO...
      ..OOOOOOOOOOO...
      ..ooOOOOOOOoo...
      ...oo.....oo....
      ...SS.....SS....
      ...BB.....BB....
    `),
    walk: grid(`
      ...HHHHHHHHHH...
      ..HHHHHHHHHHHH..
      ..HHsssssssHH...
      .HHSSSSSSSSSHH..
      .HhSBSWSBSWShH..
      .HhSSSSSSSSSh...
      .HhSSRSSSSRSh...
      .HHsSSSSSSSsh...
      .HHOOOOOOOOOH...
      .HOOOOOOOOOOO...
      ..OOOAAAAAOOO...
      ..OOOOOOOOOOO...
      ..ooOOOOOOOoo...
      ...oo.....oo....
      ...SS......SS...
      ..BB.......BBB..
    `),
  },
  braids: {
    idle: grid(`
      ....HHHHHHHH....
      ...HHHHHHHHHH...
      ..HHsssssssHH...
      .HHSSSSSSSSSHH..
      hHhSBSWSBSWShHh.
      hHhSSSSSSSSSh.h.
      hHhSSRSSSSRSh.h.
      hH.sSSSSSSSshh..
      .H..OOOOOOOOH...
      ....OOOOOOOOO...
      ....OOAAAAAOO...
      ....OOOOOOOOO...
      ....ooOOOOOoo...
      .....oo...oo....
      .....SS...SS....
      .....BB...BB....
    `),
    walk: grid(`
      ....HHHHHHHH....
      ...HHHHHHHHHH...
      ..HHsssssssHH...
      .HHSSSSSSSSSHH..
      hHhSBSWSBSWShHh.
      hHhSSSSSSSSSh.h.
      hHhSSRSSSSRSh.h.
      hH.sSSSSSSSshh..
      .H..OOOOOOOOH...
      ....OOOOOOOOO...
      ....OOAAAAAOO...
      ....OOOOOOOOO...
      ....ooOOOOOoo...
      .....oo...oo....
      .....SSS...SS...
      ....BBB....BB...
    `),
  },
  turban: {
    idle: grid(`
      ....AAAAAAAA....
      ...AAAAAAAAAA...
      ..AAOOOOOOOAA...
      ..AOOOOOOOOOA...
      ..AOOAAAAAOOA...
      ..ASSSSSSSSSA...
      ..hSBSWSBSWSh...
      ..hSSSSSSSSSh...
      ..hSSRSSSSRSh...
      ...sSSSSSSSs....
      ...OOOOOOOOO....
      ..OOOOOOOOOOO...
      ..OOOAAAAAOOO...
      ..OOOOOOOOOOO...
      ...oo.....oo....
      ...BB.....BB....
    `),
    walk: grid(`
      ....AAAAAAAA....
      ...AAAAAAAAAA...
      ..AAOOOOOOOAA...
      ..AOOOOOOOOOA...
      ..AOOAAAAAOOA...
      ..ASSSSSSSSSA...
      ..hSBSWSBSWSh...
      ..hSSSSSSSSSh...
      ..hSSRSSSSRSh...
      ...sSSSSSSSs....
      ...OOOOOOOOO....
      ..OOOOOOOOOOO...
      ..OOOAAAAAOOO...
      ..OOOOOOOOOOO...
      ...oo......oo...
      ..BB.......BBB..
    `),
  },
  hood: {
    idle: grid(`
      ...OOOOOOOOOO...
      ..OOOOOOOOOOOO..
      ..OOoooooooOOO..
      ..OOosssssoOOO..
      ..OoSSSSSSSoOO..
      ..OoSBSWSBSWoO..
      ..OoSSSSSSSSoO..
      ..OoSSRSSSSRoO..
      ..OosSSSSSSSso..
      ..OOOOOOOOOOOO..
      ..OOOOAAAAOOOO..
      ..OOOOOOOOOOOO..
      ..ooOOOOOOOOoo..
      ...oo.....oo....
      ...SS.....SS....
      ...BB.....BB....
    `),
    walk: grid(`
      ...OOOOOOOOOO...
      ..OOOOOOOOOOOO..
      ..OOoooooooOOO..
      ..OOosssssoOOO..
      ..OoSSSSSSSoOO..
      ..OoSBSWSBSWoO..
      ..OoSSSSSSSSoO..
      ..OoSSRSSSSRoO..
      ..OosSSSSSSSso..
      ..OOOOOOOOOOOO..
      ..OOOOAAAAOOOO..
      ..OOOOOOOOOOOO..
      ..ooOOOOOOOOoo..
      ...oo......oo...
      ...SS.......SS..
      ..BB........BB..
    `),
  },
  curls: {
    idle: grid(`
      ...HHHHHHHHHH...
      ..HHHHHHHHHHHH..
      .HHHHHHHHHHHHHH.
      .HhHhssssssHhHh.
      ..hSSSSSSSSSh...
      ..hSBSWSBSWSh...
      ..hSSSSSSSSSh...
      ..hSSRSSSSRSh...
      ...sSSSSSSSs....
      ...OOOOOOOOO....
      ..OOOOOOOOOOO...
      ..OOOAAAAAOOO...
      ..OOOOOOOOOOO...
      ..ooOOOOOOOoo...
      ...SS.....SS....
      ...BB.....BB....
    `),
    walk: grid(`
      ...HHHHHHHHHH...
      ..HHHHHHHHHHHH..
      .HHHHHHHHHHHHHH.
      .HhHhssssssHhHh.
      ..hSSSSSSSSSh...
      ..hSBSWSBSWSh...
      ..hSSSSSSSSSh...
      ..hSSRSSSSRSh...
      ...sSSSSSSSs....
      ...OOOOOOOOO....
      ..OOOOOOOOOOO...
      ..OOOAAAAAOOO...
      ..OOOOOOOOOOO...
      ..ooOOOOOOOoo...
      ...SSS.....SS...
      ..BBB......BB...
    `),
  },
};

const drawGrid = (
  rows: string[],
  palette: FramePalette,
  scale: number,
): HTMLCanvasElement => {
  const canvas = document.createElement('canvas');
  canvas.width = FRAME_SIZE * scale;
  canvas.height = FRAME_SIZE * scale;
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  for (let y = 0; y < FRAME_SIZE; y++) {
    const row = rows[y] ?? '';
    for (let x = 0; x < FRAME_SIZE; x++) {
      const ch = row.charAt(x);
      let color: string | null = null;
      switch (ch) {
        case 'S': color = palette.S; break;
        case 's': color = palette.s; break;
        case 'H': color = palette.H; break;
        case 'h': color = palette.h; break;
        case 'O': color = palette.O; break;
        case 'o': color = palette.o; break;
        case 'A': color = palette.A; break;
        case 'B': color = palette.B; break;
        case 'W': color = palette.W; break;
        case 'R': color = palette.R; break;
        default: color = null;
      }
      if (!color) continue;
      ctx.fillStyle = color;
      ctx.fillRect(x * scale, y * scale, scale, scale);
    }
  }
  return canvas;
};

const paletteFromAvatar = (avatar: Avatar): FramePalette => ({
  S: avatar.palette.skin,
  s: avatar.palette.skinShade,
  H: avatar.palette.hair,
  h: avatar.palette.hairShade,
  O: avatar.palette.outfit,
  o: avatar.palette.outfitShade,
  A: avatar.palette.accent,
  B: '#1a1a1a',
  W: '#fbf5e1',
  R: '#e3848a',
});

/**
 * Returns a {idle, walk, celebrate} sprite-strip canvas (3 frames side by
 * side) ready to be turned into a Phaser sprite sheet. We bake a few
 * "celebrate" frames by re-using the idle artwork.
 */
export const buildAvatarSpriteSheet = (avatar: Avatar, scale = 4): HTMLCanvasElement => {
  const palette = paletteFromAvatar(avatar);
  const frames = AVATAR_FRAMES[avatar.style];

  const sheet = document.createElement('canvas');
  sheet.width = FRAME_SIZE * scale * 4;
  sheet.height = FRAME_SIZE * scale;
  const ctx = sheet.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;

  const idle = drawGrid(frames.idle, palette, scale);
  const walk = drawGrid(frames.walk, palette, scale);
  // For celebrate frames we offset the idle a few px up.
  const celebrate = document.createElement('canvas');
  celebrate.width = idle.width;
  celebrate.height = idle.height;
  const cctx = celebrate.getContext('2d')!;
  cctx.imageSmoothingEnabled = false;
  cctx.drawImage(idle, 0, -2 * scale);

  ctx.drawImage(idle, 0, 0);
  ctx.drawImage(walk, FRAME_SIZE * scale, 0);
  ctx.drawImage(idle, FRAME_SIZE * scale * 2, 0);
  ctx.drawImage(celebrate, FRAME_SIZE * scale * 3, 0);
  return sheet;
};

/**
 * Stand-alone <canvas> previews used in the avatar selection menu so we
 * can show original pixel art without loading any external image asset.
 */
export const buildAvatarPreview = (avatar: Avatar, scale = 6): HTMLCanvasElement => {
  const palette = paletteFromAvatar(avatar);
  const frames = AVATAR_FRAMES[avatar.style];
  return drawGrid(frames.idle, palette, scale);
};
